development:
  clients:
    default:
      uri: "mongodb://heroku_2b4zpfgb:dq61u1nu20tehva26vchrohn1v@ds257668.mlab.com:57668/heroku_2b4zpfgb"
      options:
        retry_writes: false
        connect_timeout: 15
        wait_queue_timeout: 15
  options:
    raise_not_found_error: false
test:
  clients:
    default:
      database: archi_dev_db
      hosts:
        - localhost:27017
      options:
        raise_not_found_error: false
        read:
          mode: :primary
        max_pool_size: 1
production:
  options:
    raise_not_found_error: false
  clients:
    default:
      uri: "mongodb://heroku_2b4zpfgb:dq61u1nu20tehva26vchrohn1v@ds257668.mlab.com:57668/heroku_2b4zpfgb"
      options:
        raise_not_found_error: false
        retry_writes: false
        connect_timeout: 15
        wait_queue_timeout: 15
